#!usr/bin/env ruby
puts "Enter a number of iterations."
input = gets.chomp
w_0 = 1
w_1 = 1
w_2 = 1
x1_ary = [1, 1, 2, -13, 0]
x2_ary = [1, 2, -1, -4, 0]
x3_ary = [1, 5, -2, 5, 0]
x4_ary = [1, 3, -1, 0, 0]
x5_ary = [1, 8, 2, 1, 0]

input = input.to_i
iter = 0
while(iter < input) do

x1_ary[4] = w_0*x1_ary[0] + w_1*x1_ary[1] + w_2*x1_ary[2]
x2_ary[4] = w_0*x2_ary[0] + w_1*x2_ary[1] + w_2*x2_ary[2]
x3_ary[4] = w_0*x3_ary[0] + w_1*x3_ary[1] + w_2*x3_ary[2]
x4_ary[4] = w_0*x4_ary[0] + w_1*x4_ary[1] + w_2*x4_ary[2]
x5_ary[4] = w_0*x5_ary[0] + w_1*x5_ary[1] + w_2*x5_ary[2]

w_0 = w_0 + 0.01*((x1_ary[0]*(x1_ary[3]-x1_ary[4])+x2_ary[0]*(x2_ary[3]-x2_ary[4])+x3_ary[0]*(x3_ary[3]-x3_ary[4])+x4_ary[0]*(x4_ary[3]-x4_ary[4])+x5_ary[0]*(x5_ary[3]-x5_ary[4])))
w_1 = w_1 + 0.01*((x1_ary[1]*(x1_ary[3]-x1_ary[4])+x2_ary[1]*(x2_ary[3]-x2_ary[4])+x3_ary[1]*(x3_ary[3]-x3_ary[4])+x4_ary[1]*(x4_ary[3]-x4_ary[4])+x5_ary[1]*(x5_ary[3]-x5_ary[4])))
w_2 = w_2 + 0.01*((x1_ary[2]*(x1_ary[3]-x1_ary[4])+x2_ary[2]*(x2_ary[3]-x2_ary[4])+x3_ary[2]*(x3_ary[3]-x3_ary[4])+x4_ary[2]*(x4_ary[3]-x4_ary[4])+x5_ary[2]*(x5_ary[3]-x5_ary[4])))

iter = iter + 1
end

puts "W1 SHOULD BE:"
puts 1-0.01*(1*(-13-4)+1*(-4-2)+1*(5-4)+1*(0-3)+1*(1-11))
puts "H(x1)"
puts x1_ary
puts "H(x2)"	
puts x2_ary
puts "H(x3)"	
puts x3_ary
puts "H(x4)"	
puts x4_ary
puts "H(x5)"	
puts x5_ary
puts "W1 ="	
puts w_0.to_s
puts "W2 ="
puts w_1.to_s
puts "W3 ="
puts w_2.to_s

